apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
  # these labels are replicaset labels
  labels:
    project: roboshop
   
    tier: frontend
    component: frontend
    version: green
 

spec:
  replicas: 4
  selector: 
    # using these labels replica set selects the pod    
    matchLabels:
      tier: frontend
      component: frontend
      version: green

    # this is pod definition, pod is subset of replica
  template:
    metadata: 
      labels:
         tier: frontend
         component: frontend
         version: green
    spec:
     containers:
     - name: nginx-green
       image: kopparthiprasanna/blue-green:0.0.2