apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::370400270361:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-ZExOjYcpIov6
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
   # add this name here is the username and and roboshop-trinee is role name
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::370400270361:user/prassu
      username: prassu  
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::370400270361:user/phani
      username: phani  
    
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::160885265516:user/prasa
      username: prasa
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::160885265516:user/pr
      username: pr

kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-03T08:30:20Z"
  name: aws-auth
  namespace: kube-system
 # resourceVersion: "1140"
  uid: 67e41d24-9a98-4a42-90e8-38e311e3adc8