apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::370400270361:role/eksctl-roboshop-addon-iamserviceaccount-robos-Role1-CqpRC8BKBeIE
  
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: roboshop-secret-reader
  namespace: roboshop
  

