apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: roboshop
spec:
  serviceAccountName: roboshop-secret-reader
  containers:
  - name: aws-cli
    image: amazon/aws-cli # we have to give / or we will get imagepulleror.
    command: ["sleep","2000"]