[mongodb]
mongodb-dev.prasanna.fun

[catalogue]
catalogue-dev.prasanna.fun

[user]
user-dev.prasanna.fun

[cart]
cart-dev.prasanna.fun
[redis]
redis-dev.prasanna.fun
[payment]
payment-dev.prasanna.fun
[mysql]
mysql-dev.prasanna.fun
[shipping]
shipping-dev.prasanna.fun

[rabbitmq]
rabbitmq-dev.prasanna.fun


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.prasanna.fun
REDIS_HOST=redis-dev.prasanna.fun
MYSQL_HOST=mysql-dev.prasanna.fun
RABBITMQ_HOST=rabitmq-dev.prasanna.fun
CART_HOST=cart-dev.prasanna.fun
CATALOGUE_HOST=catalogue-dev.prasanna.fun
USER_HOST=user-dev.prasanna.fun
SHIPPING_HOST=shipping-dev.prasanna.fun
PAYMENT_HOST=payment-dev.prasanna.fun


