[mongodb]
mongodb-dev.prasanna.fun

[catalogue]
catalogue-dev.prasanna.fun

[user]
user-dev.prasanna.fun

[cart]
cart-dev.prasanna.fun
[redis]
redis-dev.prasanna.fun
[payment]
payment-dev.prasanna.fun
[mysql]
mysql-dev.prasanna.fun
[shipping]
shipping-dev.prasanna.fun


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.prasanna.fun


