ARG version
FROM almalinux:${version:-8}
ARG COURSE="Docker" \
    TRAINER="siva" \
    DURATION="140HRS" \
    AUTHOR="JoinDevops" 
RUN echo "Trainer is: ${TRAINER}" 
# version is only work for from first line after taht it won't apss to second line.
#RUN echo "Trainer is: ${TRAINER}", version is: ${version}" 
CMD ["sleep","100"]  

