[local]
localhost

#here change mongodb-dev.daws88s.online to localhost


[mongodb]
localhost

[catalogue]
localhost

[redis]
localhost # for redis

[user]
localhost

[cart]
localhost

[mysql]
localhost

[shipping]
localhost

[rabbitmq]
localhost

[payment]
localhost

[frontend]
localhost
