- name: app setup
  ansible.builtin.import_role:
    name: app-setup.yaml
    tasks_from: common

- name: python setup
  ansible.builtin.import_role:
    name: python-setup.yaml
    tasks_from: common    

- name: systemd setup
  ansible.builtin.import_role:
    name: systemd-setup.yaml
    tasks_from: common


- name: start and enable
  ansible.builtin.service:
     name: payment
     state: restarted
     enabled: yes    



