// # hybrid

// pipeline {
//     agent any
//     stages {
//         stage('Build') {
//             steps {
//                 script{
//                     sh """
//                         echo "building"
//                     """
//                 }
//             }
//         }
//         stage('Test') {
//             steps {
//                 script{
//                     sh """
//                         echo "testing"
//                     """
//                 }
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 script{
//                     sh """
//                         echo "deploying"
//                     """
//                 }
//             }
//         }
//     }
// }


// agent


// pipeline {
//     agent {
//         node {
//             label 'ROBOSHOP'
//         }
//     }
//     stages {
//         stage('Build') {
//             steps {
//                 script{
//                     sh """
//                         echo "building"
//                     """
//                 }
//             }
//         }
//         stage('Test') {
//             steps {
//                 script{
//                     sh """
//                         echo "testing"
//                     """
//                 }
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 script{
//                     sh """
//                         echo "deploying"
//                     """
//                 }
//             }
//         }
//     }
// }




//3.post-build






// pipeline {
//     agent {
//         node {
//             label 'ROBOSHOP'
//         }
//     }
//     stages {
//         stage('Build') {
//             steps {
//                 script{
//                     sh """
//                         echo "building"   
//                     """
//                 }
//             }
//         }
//         stage('Test') {
//             steps {
//                 script{
//                     sh """
//                         echo "testing"
//                     """
//                 }
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 script{
//                     sh """
//                         echo "deploying"
//                     """
//                 }
//             }
//         }
//     }
//     //postbuild always--even pipeline success or fail it will run

//     post {
//         always {
//             echo 'I will always say Hello again!'
//         }
//         success {
//             echo "pipeline success"
//         }
//         failure {
//             echo "pipeline failure"
//         }
    
    
//     }
// }


// env var

// pipeline {
//     agent {
//         node {
//             label 'ROBOSHOP'
//         }
//     }
//     environment {
//         COURSE = "Jenkins"
//     }
//     stages {
//         stage('Build') {
//             steps {
//                 script{
//                     sh """
//                         echo "building" 
//                         echo $COURSE  

//                     """
//                 }
//             }
//         }
//         stage('Test') {
//             steps {
//                 script{
//                     sh """
//                         echo "testing"
//                     """
//                 }
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 script{
//                     sh """
//                         echo "deploying"
//                     """
//                 }
//             }
//         }
//     }
//     //postbuild always--even pipeline success or fail it will run

//     post {
//         always {
//             echo 'I will always say Hello again!'
//         }
//         success {
//             echo "pipeline success"
//         }
//         failure {
//             echo "pipeline failure"
//         }
    
    
//     }
// }

// concurent builds

pipeline {
    agent {
        node {
            label 'ROBOSHOP'
        }
    }
    environment {
        COURSE = "Jenkins"
    }
    options {
        disableConcurrentBuilds()
    }
    stages {
        stage('Build') {
            steps {
                script{
                    sh """
                        echo "building" 
                        echo $COURSE  
                        sleep 5

                    """
                }
            }
        }
        stage('Test') {
            steps {
                script{
                    sh """
                        echo "testing"
                    """
                }
            }
        }
        stage('Deploy') {
            steps {
                script{
                    sh """
                        echo "deploying"
                    """
                }
            }
        }
    }
    //postbuild always--even pipeline success or fail it will run

    post {
        always {
            echo 'I will always say Hello again!'
        }
        success {
            echo "pipeline success"
        }
        failure {
            echo "pipeline failure"
        }
    
    
    }
}