// # hybrid

// pipeline {
//     agent any
//     stages {
//         stage('Build') {
//             steps {
//                 script{
//                     sh """
//                         echo "building"
//                     """
//                 }
//             }
//         }
//         stage('Test') {
//             steps {
//                 script{
//                     sh """
//                         echo "testing"
//                     """
//                 }
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 script{
//                     sh """
//                         echo "deploying"
//                     """
//                 }
//             }
//         }
//     }
// }


// agent


// pipeline {
//     agent {
//         node {
//             label 'ROBOSHOP'
//         }
//     }
//     stages {
//         stage('Build') {
//             steps {
//                 script{
//                     sh """
//                         echo "building"
//                     """
//                 }
//             }
//         }
//         stage('Test') {
//             steps {
//                 script{
//                     sh """
//                         echo "testing"
//                     """
//                 }
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 script{
//                     sh """
//                         echo "deploying"
//                     """
//                 }
//             }
//         }
//     }
// }




//3.post-build






pipeline {
    agent {
        node {
            label 'ROBOSHOP'
        }
    }
    stages {
        stage('Build') {
            steps {
                script{
                    sh """
                        echo "building"
                    """
                }
            }
        }
        stage('Test') {
            steps {
                script{
                    sh """
                        echo "testing"
                    """
                }
            }
        }
        stage('Deploy') {
            steps {
                script{
                    sh """
                        echo "deploying"
                    """
                }
            }
        }
    }

    post {
        always {
            echo 'I will always say Hello again!'
        }
    }
    success {
        echo "pipeline success"
    }
}