// # hybrid

// pipeline {
//     agent any
//     stages {
//         stage('Build') {
//             steps {
//                 script{
//                     sh """
//                         echo "building"
//                     """
//                 }
//             }
//         }
//         stage('Test') {
//             steps {
//                 script{
//                     sh """
//                         echo "testing"
//                     """
//                 }
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 script{
//                     sh """
//                         echo "deploying"
//                     """
//                 }
//             }
//         }
//     }
// }


// agent


// pipeline {
//     agent {
//         node {
//             label 'ROBOSHOP'
//         }
//     }
//     stages {
//         stage('Build') {
//             steps {
//                 script{
//                     sh """
//                         echo "building"
//                     """
//                 }
//             }
//         }
//         stage('Test') {
//             steps {
//                 script{
//                     sh """
//                         echo "testing"
//                     """
//                 }
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 script{
//                     sh """
//                         echo "deploying"
//                     """
//                 }
//             }
//         }
//     }
// }




//3.post-build






// pipeline {
//     agent {
//         node {
//             label 'ROBOSHOP'
//         }
//     }
//     stages {
//         stage('Build') {
//             steps {
//                 script{
//                     sh """
//                         echo "building"   
//                     """
//                 }
//             }
//         }
//         stage('Test') {
//             steps {
//                 script{
//                     sh """
//                         echo "testing"
//                     """
//                 }
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 script{
//                     sh """
//                         echo "deploying"
//                     """
//                 }
//             }
//         }
//     }
//     //postbuild always--even pipeline success or fail it will run

//     post {
//         always {
//             echo 'I will always say Hello again!'
//         }
//         success {
//             echo "pipeline success"
//         }
//         failure {
//             echo "pipeline failure"
//         }
    
    
//     }
// }


// env var

// pipeline {
//     agent {
//         node {
//             label 'ROBOSHOP'
//         }
//     }
//     environment {
//         COURSE = "Jenkins"
//     }
//     stages {
//         stage('Build') {
//             steps {
//                 script{
//                     sh """
//                         echo "building" 
//                         echo $COURSE  

//                     """
//                 }
//             }
//         }
//         stage('Test') {
//             steps {
//                 script{
//                     sh """
//                         echo "testing"
//                     """
//                 }
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 script{
//                     sh """
//                         echo "deploying"
//                     """
//                 }
//             }
//         }
//     }
//     //postbuild always--even pipeline success or fail it will run

//     post {
//         always {
//             echo 'I will always say Hello again!'
//         }
//         success {
//             echo "pipeline success"
//         }
//         failure {
//             echo "pipeline failure"
//         }
    
    
//     }
// }

// concurent builds

// pipeline {
//     agent {
//         node {
//             label 'ROBOSHOP'
//         }
//     }
//     environment {
//         COURSE = "Jenkins"
//     }
//     options {
//         disableConcurrentBuilds()
//         timeout(time: 5, unit: 'SECONDS')

//     }
//     stages {
//         stage('Build') {
//             steps {
//                 script{
//                     sh """
//                         echo "building" 
//                         echo $COURSE  
//                         sleep 10

//                     """
//                 }
//             }
//         }
//         stage('Test') {
//             steps {
//                 script{
//                     sh """
//                         echo "testing"
//                     """
//                 }
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 script{
//                     sh """
//                         echo "deploying"
//                     """
//                 }
//             }
//         }
//     }
//     //postbuild always--even pipeline success or fail it will run

//     post {
//         always {
//             echo 'I will always say Hello again!'
//         }
//         success {
//             echo "pipeline success"
//         }
//         failure {
//             echo "pipeline failure"
//         }
    
    
//     }
// }



// parameters

pipeline {
    agent {
        node {
            label 'ROBOSHOP' 
        } 
    }
    environment {
        COURSE = "Jenkins"
    }
    options {
        disableConcurrentBuilds()
        timeout(time: 5, unit: 'MINUTES')

    }
    
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }

    stages {
        stage('Build') {
            steps {
                script{
                    sh """
                        echo "building" 
                        echo $COURSE  
                        sleep 10

                    """
                }
            }
        }
        stage('Test') {
            steps {
                script{
                    sh """
                        echo "testing"
                        echo "Hello ${params.PERSON}"
                        echo "Biography: ${params.BIOGRAPHY}"
                        echo "Toggle: ${params.TOGGLE}" 
                        echo "Choice: ${params.CHOICE}" 
                        echo "Password: ${params.PASSWORD}"
                    """
                }
            }
        }
        stage('Deploy') {
            steps {
                script{
                    sh """
                        echo "deploying"
                    """
                }
            }
        }
    }
    //postbuild always--even pipeline success or fail it will run

    post {
        always {
            echo 'I will always say Hello again!'
        }
        success {
            echo "pipeline success"
        }
        failure {
            echo "pipeline failure"
        }
    
    
    }
}












