apiVersion: v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: frontend
    component: frontend

spec:
  replicas: 1
  selector: 
    # using these labels replica set selects the pod    
    matchLabels:
     project: roboshop
     tier: frontend
     component: frontend

    # this is pod definition, pod is subset of replica
  template:
    metadata: 
      labels:
        project: roboshop
        tier: frontend
        component: frontend
    spec:
     containers:
     - name: frontend
       image: kopparthiprasanna/frontend:1.4.0
       imagePullPolicy: Always # this is safe to pull everytime, tehre may be images with same version rebuild and pushed.
    # Adding resources and probes are the best practices.   
       resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi" 
        
       readinessProbe:
        # httpGet:
        #   path: /health
        #   port: 8080
     # here you can give httpget ot tcp socket
        tcpSocket:
          port: 8080
        failureThreshold: 2
        periodSeconds: 10
        initialDelaySeconds: 15   
       livenessProbe:
        httpGet:
          path: /
          port: 80  
        failureThreshold: 2
        periodSeconds: 10
        initialDelaySeconds: 10  
      

---

apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: roboshop
  labels:
        project: roboshop
        tier: frontend
        component: frontend

spec:  
  type: LoadBalancer
  selector:
  # labels are used as selectors.so service add the pod which is having these labels.
    project: roboshop
    tier: frontend
    component: frontend

  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port  
