- name: var preference
  hosts: local
  connection: local
  vars:
    NAME: :ansible form play
  vars_files:
  - name: from files
  - course.yaml  
  vars_prompt:
  - name: NAME
    prompt: please enter ur name
    private: false
  tasks:
  - name: print name from taks level
    # vars:
    #   NAME: "ansible from task" 
    ansible.builtin.debug:
      msg: "hi {{NAME}}" 


# args cmd
# tasks