- name: demo on datatypes
  hosts: local
  connection: local
  vars:
   PROGRAM: "devsecops" #STRING
   DURATION: 140 #INT
   IS_LIVE: true #BOOL
   DETAILS: #MAP
    MONTHS: 4
    TRAINER: "Siva"
   TOPICS: #LIST
   - linux
   - shell
   - terrform
  tasks:
  - name: print var
    ansible.builtin.debug:
     msg: |
       program: {{PROGRAM}}
       duration: {{DURATION}}
       topics: {{TOPICS}}
       is_live: {{IS_LIVE}}
       details: {{DETAILS}}
