- name: check conditions
  host: local
  connections: local
  vars:
    NUMBER_OF_SESSIONS: 7
    IS_LIVE: true
  tasks:
  - name: is ansible more than 5 sessions and is it live
    ansible.buitin.debug:
     msg: "yes it is more than 5"
    when: NUMBER_OF_SESSIONS > 5 