- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: linux, shell, terraform
    course: "devops WITH"
    myIP: 256.780.770.654
    tagsMap:
      name: ansible
      project: roboshop
      component: catalogue

    tagsList:
     [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]

  
  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: "hi prassu, {{GREETING | default('good mrng')}}"
  
  - name: convert string to list
    ansible.builtin.debug:
     msg: "{{ topics  |  split(',') }}"

  - name: convert map to list
    ansible.builtin.debug:
     msg: "{{ tagsMap | dict2items }}"  


  - name: convert list to map
    ansible.builtin.debug:
     msg: "{{ tagsList | items2dict }}"  

        
# convert yaml to json. but first take yaml into one variable then convert

  - name: read students.yaml
    ansible.builtin.set_fact:  #setting the var
      student_yaml: "{{ lookup('file', 'students.yaml' ) | from_yaml }}"
    
  
  - name: convert yaml to json
    ansible.builtin.debug:
     msg: "{{ student_yaml | to_nice_json }}"

  - name: convert to uppercase
    ansible.builtin.debug:
     msg: "{{ course | upper }}"

  - name: convert to lowercase
    ansible.builtin.debug:
     msg: "{{ course | lower }}"   

  - name: check ip address 
    ansible.builtin.debug:
     msg: "{{ myIP | ansible.utils.ipv4 }}"   



# 1.  msg: "{{ topics  |  split(',') }}"

#  [localhost] => {
#     "msg": [
#         "linux",
#         " shell",
#         " terraform"       


# 2. map to string
# [
#         {
#             "key": "name",
#             "value": "ansible"
#         },
#         {
#             "key": "project",
#             "value": "roboshop"
#         },
#         {
#             "key": "component",
#             "value": "catalogue"
#         }
#     ]
# }

# 3. list to map

# {
#         "component": "catalogue",
#         "name": "ansible",
#         "project": "roboshop"
#     }


# TASK [convert yaml to json] ***********************************************************
# ok: [localhost] => {
#     "msg": "[\n    {\n        \"addresses\": [\n            {\n                \"flatNumber\": \"3-131\",\n                \"street\": \"muthyalamma temple\"\n            },\n            {\n                \"flatNumber\": \"3-132\",\n                \"street\": \"muthyalamma temple\"\n            }\n        ],\n        \"dob\": \"2001-05-08\",\n        \"mobileNumber\": 123232343,\n        \"name\": \"prasanna kopparthi\"\n    },\n    {\n        \"addresses\": [\n            {\n                \"flatNumber\": \"3-131\",\n                \"street\": \"muthyalamma temple\"\n            },\n            {\n                \"flatNumber\": \"3-132\",\n                \"street\": \"muthyalamma temple\"\n            }\n        ],\n        \"dob\": \"2001-05-08\",\n        \"mobileNumber\": 123232343,\n        \"name\": \"prasanna\"\n    }\n]"
# }

# TASK [convert to uppercase] ***********************************************************
# ok: [localhost] => {
#     "msg": "DEVOPS WITH"
# }

# TASK [convert to lowercase] ***********************************************************
# ok: [localhost] => {
#     "msg": "devops with"
# }

# TASK [check ip address] ***************************************************************
# ok: [localhost] => {
#     "msg": false
# }

