# - name: var prefernce
#   hosts: local
#   connection: local
#   become: yes
#   vars:
#    NAME: "prassu from playbook"
#   vars_files:
#   - course.yaml
#   vars_prompt:
#   - name: NAME
#     prompt: pleas enter ur name
#     private: false
#   tasks:
#   - name: variables form task
#     vars:
#      NAME: "Vars form tasks"
#     ansible.builtin.debug:
#      msg: "username is: {{ NAME }}"   



# - name: demo on data types
#   hosts: local
#   connection: local
#   become: yes
#   vars:
#    PROGRAM: "devsecops" 
#    DURATION: 140
#    IS_LIVE: true
#    DETAILS:
#     MONTHS: 4
#     TRAINER: "SIV" 
#    TOPICS:
#    - Linux
#    - Shell
#   tasks:
#   - name: print var
#     ansible.builtin.debug:
#      msg: |
#       program: {{ PROGRAM }}  
#       duration: {{  DURATION }}


# - name: demo on conditions
#   hosts: local
#   connection: local
#   become: yes
#   vars:
#    IS_LIVE: true
#   tasks:
#   - name: is it live
#     ansible.builtin.debug:
#       msg: "yes it is live"
#     when: IS_LIVE




# - name: demo on conditions
#   hosts: local
#   connection: local
#   become: yes
#   vars:
#    NUMBER_OF_SESSIONS: 7
#   tasks:
#   - name: is it live
#     ansible.builtin.debug:
#       msg: "yes it is live"
#     when: NUMBER_OF_SESSIONS > 5


# - name: gather facts
#   hosts: local
#   connection: local
#   become: yes
#   tasks:
#   - name: gathering teh facts
#     ansible.builtin.debug:
#      msg: "{{ ansible_facts }}"

#   - name: check redhat or not
#     ansible.builtin.debug:
#      msg: "package manager is redhat"
#     when: ansible_facts.os_family == "RedHat"


# - name: shell vs cmd
#   hosts: local
#   connection: local
#   tasks:
#   - name: shell
#     ansible.builtin.shell: cat /etc/passwd | grep "root"
#     register: user_sample

#   - name: print
#     ansible.builtin.debug:
#      msg: "{{ user_sample }}"  

   

  
#   - name: cmd
#     ansible.builtin.command: date
#     register: user

#   - name: print
#     ansible.builtin.debug:
#      msg: "{{ user }}"  
   
  
#   - name: cmd
#     ansible.builtin.command: cat /etc/passwd | grep "root"
#     register: user_sample

#   - name: print
#     ansible.builtin.debug:
#      msg: "{{ user_sample }}"   


- name: loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: loops
    ansible.builtin.debug:
     msg: " hello {{ item}}"
    loop:
    - p
    - pr
    - pra