
pipeline {
    agent {
        node {
            label 'roboshop' 
        } 
    }

    environment {
        appVersion = ""
        ACC_ID = "864981724645"
        region = "us-east-1"
    }
    
    options {
        timeout(time: 5, unit: 'MINUTES')
    }

    stages {
        stage('Read version') {
            steps {
                dir('catalogue') {
                    script{
                        // load and parse the json file
                        def packageJson = readJSON file: 'package.json'

                        //Access fields directly
                        appVersion = packageJson.version
                        echo "Building version ${appVersion}" 
                    }
               
                }   
            
            
            }
       
       
        }
        stage('Build image') {
            steps {
                  dir('catalogue') {
                        script{
                            withAWS( credentials: 'aws-creds', region: "${region}") {
                        
                            // commands here have AWS authentication 
                                sh """
                                    aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${ACC_ID}.dkr.ecr.${region}.amazon.com
                                    docker build -t ${ACC_ID}.dkr.ecr.${region}.amazonaws.com/roboshop/catalogue:${appVersion} .
                                    docker push ${ACC_ID}.dkr.ecr.${region}.amazonaws.com/roboshop/catalogue:${appVersion} 
                                """
                            }
                        }
                    }
                }
            }
        }
    
    

    post {
        always {
            echo 'I will always say Hello again!'
        }
        success {
            echo "pipeline success"
        }
        failure {
            echo "pipeline failure"
        }

        
    }
}












