
pipeline {
    agent {
        node {
            label 'roboshop' 
        } 
    }

    environment {
        appVersion = ""
    }
    
    options {
        timeou(time: 5, unit: 'MINUTES')
    }

    stages {
        stage('Read version') {
            steps {
                script{
                    // load and parse the json file
                    def packageJson = readJSON file: 'package.json'

                    //Access fields directly
                    appVersion = packageJson.version
                    echo "Building ${appName} version ${appVersion}"
                }
            }
        }
        stage('Build image') {
            steps {
                script{
                    sh """
                        docker build -t catalogue:$appVersion
                    """    
                    
                }
            }
        }
    }
    post {
        always {
            echo 'I will always say Hello again!'
        }
        success {
            echo "pipeline success"
        }
        failure {
            echo "pipeline failure"
        }

        
    }
}












