apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    tier: database
spec:
  containers:
  - name: nginx
    image: nginx

---

  # now this pod also run in sma enode as pod-1

apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    tier: backend
spec:
  affinity:
    podAffinity:
    # hard rule here we give pod-1 labels
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: tier
            operator: In
            values:
            - database
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx